<?php
//error_reporting(0);
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
include('db_connect/config.php');
require_once('jwt.php');
$result_array=array();
// $token=$_POST['token'];
// $payload = JWT::decode($token, $serverKey, array('HS256'));
// $returnArray = array('userId' => $payload->userId);
// $user_id=$returnArray['userId'];

$query=mysqli_query($conn,"select * from settings order by id desc limit 0,1");
$fetch=mysqli_fetch_assoc($query);
$result_array['id']=$fetch['id'];
$result_array['logo']=$fetch['logo'];
$result_array['banner1']=$fetch['banner1'];
$result_array['banner2']=$fetch['banner2'];
$result_array['social_twitter']=$fetch['social_twitter'];
$result_array['social_instagram']=$fetch['social_instagram'];
$result_array['social_discord']=$fetch['social_discord'];
$result_array['title']=$fetch['title'];
$result_array['content']=$fetch['content'];
$result_array['img1']=$fetch['img1'];
$result_array['section4_title']=$fetch['section4_title'];
$result_array['section4_content']=$fetch['section4_content'];
$result_array['section4_img']=$fetch['section4_img'];

$result_array['give_img1']=$fetch['give_img1'];
$result_array['give_img2']=$fetch['give_img2'];
$result_array['give_img3']=$fetch['give_img3'];
$result_array['give_content']=$fetch['give_content'];
$result_array['crypto_cunt_content']=$fetch['cryptocunt_content'];
$result_array['img2']=$fetch['img2'];
$result_array['img3']=$fetch['img3'];
$result_array['img4']=$fetch['img4'];
$result_array['avatar1']=$fetch['avatar1'];
$result_array['avatar2']=$fetch['avatar2'];
$result_array['avatar3']=$fetch['avatar3'];
$result_array['collect_img1']=$fetch['collect_img1'];
$result_array['collect_img2']=$fetch['collect_img2'];
$result_array['collect_img3']=$fetch['collect_img3'];
$result_array['collect_img4']=$fetch['collect_img4'];
$result_array['collect_content1']=$fetch['collect_content1'];
$result_array['collect_content2']=$fetch['collect_content2'];
$result_array['collect_content3']=$fetch['collect_content3'];
$result_array['collect_content4']=$fetch['collect_content4'];
$result_array['collect_title1']=$fetch['collect_title1'];
$result_array['collect_title2']=$fetch['collect_title2'];
$result_array['collect_title3']=$fetch['collect_title3'];
$result_array['collect_title4']=$fetch['collect_title4'];
$result_array['greatest_img1']=$fetch['greatest_img1'];
$result_array['greatest_img2']=$fetch['greatest_img2'];
$result_array['greatest_img3']=$fetch['greatest_img3'];
$result_array['greatest_img4']=$fetch['greatest_img4'];
$result_array['greatest_content']=$fetch['greatest_content'];
$result_array['greatest_content1']=$fetch['greatest_content1'];
$result_array['greatest_content2']=$fetch['greatest_content2'];
$result_array['greatest_content3']=$fetch['greatest_content3'];
$result_array['roadmap_per1']=$fetch['roadmap_per1'];
$result_array['roadmap_per2']=$fetch['roadmap_per2'];
$result_array['roadmap_per3']=$fetch['roadmap_per3'];
$result_array['roadmap_per4']=$fetch['roadmap_per4'];
$result_array['roadmap_per5']=$fetch['roadmap_per5'];
$result_array['roadmap_per6']=$fetch['roadmap_per6'];
$result_array['roadmap_per7']=$fetch['roadmap_per7'];
$result_array['roadmap_per8']=$fetch['roadmap_per8'];
$result_array['roadmap_per9']=$fetch['roadmap_per9'];
$result_array['roadmap_per10']=$fetch['roadmap_per10'];
$result_array['roadmap_content1']=$fetch['roadmap_content1'];
$result_array['roadmap_content2']=$fetch['roadmap_content2'];
$result_array['roadmap_content3']=$fetch['roadmap_content3'];
$result_array['roadmap_content4']=$fetch['roadmap_content4'];
$result_array['roadmap_content5']=$fetch['roadmap_content5'];
$result_array['roadmap_content6']=$fetch['roadmap_content6'];
$result_array['roadmap_content7']=$fetch['roadmap_content7'];
$result_array['roadmap_content8']=$fetch['roadmap_content8'];
$result_array['roadmap_content9']=$fetch['roadmap_content9'];
$result_array['roadmap_content10']=$fetch['roadmap_content10'];
$result_array['video_title']=$fetch['video_title'];
$result_array['video_link']=$fetch['video_link'];
$result_array['faq_title1']=$fetch['faq_title1'];
$result_array['faq_title2']=$fetch['faq_title2'];
$result_array['faq_title3']=$fetch['faq_title3'];
$result_array['faq_title4']=$fetch['faq_title4'];
$result_array['faq_title5']=$fetch['faq_title5'];
$result_array['faq_title6']=$fetch['faq_title6'];
$result_array['faq_content1']=$fetch['faq_content1'];
$result_array['faq_content2']=$fetch['faq_content2'];
$result_array['faq_content3']=$fetch['faq_content3'];
$result_array['faq_content4']=$fetch['faq_content4'];
$result_array['faq_content5']=$fetch['faq_content5'];
$result_array['faq_content6']=$fetch['faq_content6'];
$result_array['crypto_cunt_img']=$fetch['crypto_cunt_img'];
$result_array['cryptocunts']=$fetch['CryptoCunts'];
$result_array['ape']=$fetch['AnonymousApe'];
$result_array['famous']=$fetch['FamousCryptoCunt'];
$result_array['gods']=$fetch['CryptoCuntGods'];
$result_array['evolved']=$fetch['Evolved'];
$result_array['title_font']=$fetch['title_font'];
$result_array['para_font']=$fetch['para_font'];
$result_array['list_font']=$fetch['list_font'];
$result_array['button_font']=$fetch['button_font'];
$result_array['subtitle_font']=$fetch['subtitle_font'];
$result_array['title_weight']=$fetch['title_weight'];
$result_array['para_weight']=$fetch['para_weight'];
$result_array['list_weight']=$fetch['list_weight'];
$result_array['button_weight']=$fetch['button_weight'];
$result_array['subtitle_weight']=$fetch['subtitle_weight'];
$result_array['head_font']=$fetch['head_font'];
$result_array['head_weight']=$fetch['head_weight'];
$result_array['date_time']=date('Y-m-d\TH:i:s', strtotime($fetch['date_time']));
$result_array['show_date_time']=date('M d, Y H:i:s', strtotime($fetch['date_time']));


$result_array['first_title']=$fetch['first_title'];
$result_array['second_title']=$fetch['second_title'];
$result_array['avatar_title']=$fetch['avatar_title'];
$result_array['sec6_heading']=$fetch['sec6_heading'];
$result_array['sec7_heading']=$fetch['sec7_heading'];
$result_array['sec10_heading']=$fetch['sec10_heading'];
$result_array['sec11_heading']=$fetch['sec11_heading'];
$result_array['sec13_heading']=$fetch['sec13_heading'];
$result_array['sec15_heading']=$fetch['sec15_heading'];
$result_array['sec16_heading']=$fetch['sec16_heading'];
$result_array['sec17_heading']=$fetch['sec17_heading'];
$result_array['sec8_heading']=$fetch['sec8_heading'];
$result_array['sec8_content']=$fetch['sec8_content'];
$result_array['sec9_heading']=$fetch['sec9_heading'];
$result_array['sec9_content']=$fetch['sec9_content'];
$result_array['sec12_heading']=$fetch['sec12_heading'];
$result_array['sec12_content']=$fetch['sec12_content'];
$result_array['sec14_heading']=$fetch['sec14_heading'];
$result_array['sec14_content']=$fetch['sec14_content'];
$result_array['text_under10']=$fetch['text_under10'];
$result_array['sec9_img']=$fetch['sec9_img'];
$result_array['sec12_img']=$fetch['sec12_img'];
$result_array['sec14_img']=$fetch['sec14_img'];

$result = array('updated_data' => $result_array);
echo json_encode($result);
