/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://vki5ayfelzcyhdsn2g73k465fi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lmgoubtcjjg5vmgjja3f3lyznu",
    // "aws_cognito_identity_pool_id": "us-east-2:64a6f905-ce69-4fc8-a036-bfe5edbac31c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_n3UHkAHyz",
    "aws_user_pools_web_client_id": "29hmd3hugmc08de9tmsi3kbgoc",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplify-octivius-dev-232555-deployment",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
