/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createSettings = /* GraphQL */ `
  mutation CreateSettings(
    $input: CreateSettingsInput!
    $condition: ModelSettingsConditionInput
  ) {
    createSettings(input: $input, condition: $condition) {
      id
      logo
      social_twitter
      social_instagram
      social_discord
      twitter_link
      instagram_link
      discord_link
      banner1
      banner2
      first_title
      second_title
      title
      content
      img1
      img2
      img3
      img4
      avatar_title
      avatar1
      avatar2
      avatar3
      collect_img1
      collect_img2
      collect_img3
      collect_img4
      collect_content1
      collect_content2
      collect_content3
      collect_content4
      collect_title1
      collect_title2
      collect_title3
      collect_title4
      greatest_img1
      greatest_img2
      greatest_img3
      greatest_img4
      greatest_content
      greatest_content1
      greatest_content2
      greatest_content3
      roadmap_per1
      roadmap_per2
      roadmap_per3
      roadmap_per4
      roadmap_per5
      roadmap_per6
      roadmap_per7
      roadmap_per8
      roadmap_per9
      roadmap_per10
      roadmap_content1
      roadmap_content2
      roadmap_content3
      roadmap_content4
      roadmap_content5
      roadmap_content6
      roadmap_content7
      roadmap_content8
      roadmap_content9
      roadmap_content10
      video_title
      video_link
      faq_title1
      faq_title2
      faq_title3
      faq_title4
      faq_title5
      faq_title6
      faq_title7
      faq_title8
      faq_content1
      faq_content2
      faq_content3
      faq_content4
      faq_content5
      faq_content6
      faq_content7
      faq_content8
      crypto_cunt_img
      cryptocunt_content
      ape_img
      ape_content
      famous_img
      famous_content
      gods_img
      gods_content
      evolved_img
      evolved_content
      section4_title
      section4_content
      section4_img
      give_content
      give_img1
      give_img2
      give_img3
      CryptoCunts
      Evolved
      AnonymousApe
      FamousCryptoCunt
      CryptoCuntGods
      title_font
      para_font
      list_font
      subtitle_font
      button_font
      head_font
      head_weight
      title_weight
      subtitle_weight
      para_weight
      list_weight
      button_weight
      date_time
      sec6_heading
      sec7_heading
      sec10_heading
      sec11_heading
      sec13_heading
      sec15_heading
      sec16_heading
      sec17_heading
      sec8_heading
      sec8_content
      sec9_heading
      sec9_content
      text_under10
      sec12_heading
      sec12_content
      sec14_heading
      sec14_content
      sec9_img
      sec12_img
      sec14_img
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const updateSettings = /* GraphQL */ `
  mutation UpdateSettings(
    $input: UpdateSettingsInput!
    $condition: ModelSettingsConditionInput
  ) {
    updateSettings(input: $input, condition: $condition) {
      id
      logo
      social_twitter
      social_instagram
      social_discord
      twitter_link
      instagram_link
      discord_link
      banner1
      banner2
      first_title
      second_title
      title
      content
      img1
      img2
      img3
      img4
      avatar_title
      avatar1
      avatar2
      avatar3
      collect_img1
      collect_img2
      collect_img3
      collect_img4
      collect_content1
      collect_content2
      collect_content3
      collect_content4
      collect_title1
      collect_title2
      collect_title3
      collect_title4
      greatest_img1
      greatest_img2
      greatest_img3
      greatest_img4
      greatest_content
      greatest_content1
      greatest_content2
      greatest_content3
      roadmap_per1
      roadmap_per2
      roadmap_per3
      roadmap_per4
      roadmap_per5
      roadmap_per6
      roadmap_per7
      roadmap_per8
      roadmap_per9
      roadmap_per10
      roadmap_content1
      roadmap_content2
      roadmap_content3
      roadmap_content4
      roadmap_content5
      roadmap_content6
      roadmap_content7
      roadmap_content8
      roadmap_content9
      roadmap_content10
      video_title
      video_link
      faq_title1
      faq_title2
      faq_title3
      faq_title4
      faq_title5
      faq_title6
      faq_title7
      faq_title8
      faq_content1
      faq_content2
      faq_content3
      faq_content4
      faq_content5
      faq_content6
      faq_content7
      faq_content8
      crypto_cunt_img
      cryptocunt_content
      ape_img
      ape_content
      famous_img
      famous_content
      gods_img
      gods_content
      evolved_img
      evolved_content
      section4_title
      section4_content
      section4_img
      give_content
      give_img1
      give_img2
      give_img3
      CryptoCunts
      Evolved
      AnonymousApe
      FamousCryptoCunt
      CryptoCuntGods
      title_font
      para_font
      list_font
      subtitle_font
      button_font
      head_font
      head_weight
      title_weight
      subtitle_weight
      para_weight
      list_weight
      button_weight
      date_time
      sec6_heading
      sec7_heading
      sec10_heading
      sec11_heading
      sec13_heading
      sec15_heading
      sec16_heading
      sec17_heading
      sec8_heading
      sec8_content
      sec9_heading
      sec9_content
      text_under10
      sec12_heading
      sec12_content
      sec14_heading
      sec14_content
      sec9_img
      sec12_img
      sec14_img
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const deleteSettings = /* GraphQL */ `
  mutation DeleteSettings(
    $input: DeleteSettingsInput!
    $condition: ModelSettingsConditionInput
  ) {
    deleteSettings(input: $input, condition: $condition) {
      id
      logo
      social_twitter
      social_instagram
      social_discord
      twitter_link
      instagram_link
      discord_link
      banner1
      banner2
      first_title
      second_title
      title
      content
      img1
      img2
      img3
      img4
      avatar_title
      avatar1
      avatar2
      avatar3
      collect_img1
      collect_img2
      collect_img3
      collect_img4
      collect_content1
      collect_content2
      collect_content3
      collect_content4
      collect_title1
      collect_title2
      collect_title3
      collect_title4
      greatest_img1
      greatest_img2
      greatest_img3
      greatest_img4
      greatest_content
      greatest_content1
      greatest_content2
      greatest_content3
      roadmap_per1
      roadmap_per2
      roadmap_per3
      roadmap_per4
      roadmap_per5
      roadmap_per6
      roadmap_per7
      roadmap_per8
      roadmap_per9
      roadmap_per10
      roadmap_content1
      roadmap_content2
      roadmap_content3
      roadmap_content4
      roadmap_content5
      roadmap_content6
      roadmap_content7
      roadmap_content8
      roadmap_content9
      roadmap_content10
      video_title
      video_link
      faq_title1
      faq_title2
      faq_title3
      faq_title4
      faq_title5
      faq_title6
      faq_title7
      faq_title8
      faq_content1
      faq_content2
      faq_content3
      faq_content4
      faq_content5
      faq_content6
      faq_content7
      faq_content8
      crypto_cunt_img
      cryptocunt_content
      ape_img
      ape_content
      famous_img
      famous_content
      gods_img
      gods_content
      evolved_img
      evolved_content
      section4_title
      section4_content
      section4_img
      give_content
      give_img1
      give_img2
      give_img3
      CryptoCunts
      Evolved
      AnonymousApe
      FamousCryptoCunt
      CryptoCuntGods
      title_font
      para_font
      list_font
      subtitle_font
      button_font
      head_font
      head_weight
      title_weight
      subtitle_weight
      para_weight
      list_weight
      button_weight
      date_time
      sec6_heading
      sec7_heading
      sec10_heading
      sec11_heading
      sec13_heading
      sec15_heading
      sec16_heading
      sec17_heading
      sec8_heading
      sec8_content
      sec9_heading
      sec9_content
      text_under10
      sec12_heading
      sec12_content
      sec14_heading
      sec14_content
      sec9_img
      sec12_img
      sec14_img
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const createAdmin = /* GraphQL */ `
  mutation CreateAdmin(
    $input: CreateAdminInput!
    $condition: ModelAdminConditionInput
  ) {
    createAdmin(input: $input, condition: $condition) {
      id
      username
      password
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const updateAdmin = /* GraphQL */ `
  mutation UpdateAdmin(
    $input: UpdateAdminInput!
    $condition: ModelAdminConditionInput
  ) {
    updateAdmin(input: $input, condition: $condition) {
      id
      username
      password
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const deleteAdmin = /* GraphQL */ `
  mutation DeleteAdmin(
    $input: DeleteAdminInput!
    $condition: ModelAdminConditionInput
  ) {
    deleteAdmin(input: $input, condition: $condition) {
      id
      username
      password
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
